version: '3'

services:
  db:
    image: mariadb
    container_name: demo-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: demo_docker
    ports:
      - "9907:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  app:
    volumes:
      - ./apache-virtual/demo.conf:/etc/apache2/sites-available/virtual-host.conf
      - ./apache-virtual/demo.conf:/etc/apache2/sites-enabled/virtual-host.conf
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-web-app
    working_dir: /var/www/html/demo-app
    depends_on:
      - db
    ports:
      - "3000:80"