version: '3'

services:
  db:
    image: mariadb:10.4
    container_name: demo-mariadb
    restart: always
    environment:
      MARIADB_DATABASE: demo_docker
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "9907:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-web-app
    working_dir: /var/www/html
    volumes:
      - ./docker/apache-virtual/demo.conf:/etc/apache2/sites-available/virtual-host.conf
      - ./docker/apache-virtual/demo.conf:/etc/apache2/sites-enabled/virtual-host.conf
      - ./:/var/www/html
      - /var/www/html/vendor
      - ./.env.example:/var/www/html/.env
    env_file:
      - .env
    ports:
      - "3000:80"
volumes:
   db_data:
